enum Skill {
  Attack = "Attack",
  Strength = "Strength",
  Defence = "Defence",
  Ranged = "Ranged",
  Prayer = "Prayer",
  Magic = "Magic",
  Runecraft = "Runecraft",
  Construction = "Construction",
  Hitpoints = "Hitpoints",
  Agility = "Agility",
  Herblore = "Herblore",
  Thieving = "Thieving",
  Crafting = "Crafting",
  Fletching = "Fletching",
  Slayer = "Slayer",
  Hunter = "Hunter",
  Mining = "Mining",
  Smithing = "Smithing",
  Fishing = "Fishing",
  Cooking = "Cooking",
  Firemaking = "Firemaking",
  Woodcutting = "Woodcutting",
  Farming = "Farming",
  Sailing = "Sailing",
  Quest_Points = "Quest points",
  Combat_Level = "Combat level",
  Overall = "Total level",
}

export default Skill;